let cezalar = [
    {isim : "Kamu Alanlarına İzinsiz Giriş", para : 0, hapis :0, kamu :5, illegal : false, active : false, tceza : 0 },
    {isim : "Kamu Huzurunu Bozma", para : 0, hapis :0, kamu :5, illegal : false, active : false, tceza : 0 },
    {isim : "Kırmızı Işık İhlali", para : 1000, hapis :0, kamu :0, illegal : false, active : false, tceza : 1 },
    {isim : "Hız Sınırı Aşma", para : 1000, hapis :0, kamu :0, illegal : false, active : false, tceza : 1 },
    {isim : "Hatalı Park", para : 1000, hapis :0, kamu :0, illegal : false, active : false, tceza : 4 },
    {isim : "Tehlikeli Araç Kullanmak", para : 1000, hapis :0, kamu :0, illegal : false, active : false, tceza : 10 },
    {isim : "Şerit İhlali", para : 1000, hapis :0, kamu :0, illegal : false, active : false, tceza : 1 },
    {isim : "Evraksız Araç Kullanma", para : 1000, hapis :0, kamu :0, illegal : false, active : false, tceza : 1 },
    {isim : "Hatalı Sürüş", para : 1000, hapis :0, kamu :0, illegal : false, active : false, tceza : 4 },
    {isim : "Gereksiz Korna Kullanımı", para : 1000, hapis :0, kamu :0, illegal : false, active : false, tceza : 1 },
    {isim : "Darp Grişimi", para : 1000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Kaldırımda Araç Sürme", para : 1000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Alkollü Araç Kullanımı", para : 1000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Gasp", para : 1000, hapis :0, kamu :5, illegal : false, active : false, tceza : 10 },
    {isim : "Araç Çalma Girişimi", para : 1000, hapis :0, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "Çevreyi Rahatsız Etme", para : 2000, hapis :0, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "Darp", para : 2000, hapis :0, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "İzinsiz Görüntü Ve Ses Kaydı", para : 2000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Maske-Zırh-Silah Kılıfı Bulundurma", para : 3500, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Plakasız Araç Kullanma", para : 3500, hapis :0, kamu :0, illegal : false, active : false, tceza : 4 },
    {isim : "İllegal Modifiye", para : 5000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Asılsız İhbar", para : 5000, hapis :0, kamu :5, illegal : false, active : false, tceza : 0 },
    {isim : "Devlet Çalışanını Kandırma", para : 5000, hapis :0, kamu :5, illegal : false, active : false, tceza : 0 },
    {isim : "İllegal Madde Bulundurma", para : 5000, hapis :0, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "Kesici,Delici Alet Bulundurmak", para : 5000, hapis :0, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "Siber Suçlar", para : 5000, hapis :0, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "İllegal Bölgede Bulunma", para : 5000, hapis :0, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "Dolandırıcılık", para : 5000, hapis :0, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "Dur İhtarına Uymamak", para : 5000, hapis :0, kamu :15, illegal : false, active : false, tceza : 1 },
    {isim : "Çalıntı Araç Kullanma", para : 5000, hapis :0, kamu :15, illegal : false, active : false, tceza : 5 },
    {isim : "Irkçılık", para : 5000, hapis :0, kamu :15, illegal : false, active : false, tceza : 0 },
    {isim : "Magandalık", para : 5000, hapis :0, kamu :20, illegal : false, active : false, tceza : 0 },
    {isim : "Sivil Yaralama Girişimi", para : 5000, hapis :0, kamu :20, illegal : false, active : false, tceza : 0 },
    {isim : "Adam Soymak", para : 5000, hapis :0, kamu :25, illegal : false, active : false, tceza : 0 },
    {isim : "Tehdit", para : 7500, hapis :0, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "Sorgu Düzenine Uymama", para : 7500, hapis :0, kamu :10, illegal : false, active : false, tceza : 0 },
    {isim : "Kumar Oynatmak", para : 10000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "İzinsiz Yasadışı Yarış Düzenleme", para : 10000, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    {isim : "Kesici,Delici Alet Ticareti", para : 10000, hapis :0, kamu :15, illegal : false, active : false, tceza : 0 },
    {isim : "Polise Direnme+Zorluk Çıkartmak", para : 10000, hapis :0, kamu :20, illegal : false, active : false, tceza : 0 },
    {isim : "Devlet Malına Zarar Vermek", para : 10000, hapis :0, kamu :20, illegal : false, active : false, tceza : 3 },
    {isim : "Şantaj", para : 10000, hapis :0, kamu :25, illegal : false, active : false, tceza : 0 },
    {isim : "Market Soygunu", para : 10000, hapis :0, kamu :25, illegal : false, active : false, tceza : 0 },
    {isim : "Adam Kaçırma", para : 10000, hapis :0, kamu :25, illegal : false, active : false, tceza : 0 },
    {isim : "Yasadışı Ticaret", para : 10000, hapis :0, kamu :25, illegal : false, active : false, tceza : 0 },
    {isim : "Tefecilik", para : 15000, hapis :0, kamu :20, illegal : false, active : false, tceza : 0 },
    {isim : "Ruhsatsız Silah Bulundurma", para : 15000, hapis :0, kamu :20, illegal : false, active : false, tceza : 0 },
    {isim : "Kesici,Delici Alet İle Adam Yaralama", para : 15000, hapis :0, kamu :25, illegal : false, active : false, tceza : 10 },
    {isim : "Devlet Çalışanını Yaralama", para : 15000, hapis :0, kamu :30, illegal : false, active : false, tceza : 0 },
    {isim : "Yalancı Şahitlik", para : 20000, hapis :0, kamu :15, illegal : false, active : false, tceza : 0 },
    {isim : "Haraç Kesme", para : 20000, hapis :0, kamu :25, illegal : false, active : false, tceza : 10 },
    {isim : "Ateşli Silah Ticareti", para : 20000, hapis :0, kamu : 30, illegal : false, active : false, tceza : 0 },
    {isim : "Tutuklama Durumundan Kaçmak", para : 20000, hapis :0, kamu :30, illegal : false, active : false, tceza : 0 },
    {isim : "Kuyumcu Soygunu", para : 20000, hapis :0, kamu :35, illegal : false, active : false, tceza : 4 },
    {isim : "Ateşli Silah İle Cinayet Girişimi", para : 25000, hapis :0, kamu :25, illegal : false, active : false, tceza : 0 },
    {isim : "Devlet Aracını Çalma Girişimi", para : 25000, hapis :0, kamu :40, illegal : false, active : false, tceza : 0 },
    {isim : "Banka/Merkez Banka Soygunu", para : 50000, hapis :0, kamu :40, illegal : false, active : false, tceza : 0 },
    {isim : "Devlet Çalışanını Öldürme", para : 50000, hapis :0, kamu :50, illegal : false, active : false, tceza : 0 },
    {isim : "İşkence", para : 50000, hapis :0, kamu :50, illegal : false, active : false, tceza : 0 },
    
    // {isim : "Ağır Suçlar Çeteleşme", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
    // {isim : "Ağır Suçlar Örgütlenmek", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
	// {isim : "Ağır Suçlar Yasadışı Oluşum", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
	// {isim : "Ağır Suçlar Kanuna Karşı Hareketlenme", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
	// {isim : "Ağır Suçlar Terör Saldırısı", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
	// {isim : "Ağır Suçlar Terör Saldırsı Girişimi", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
	// {isim : "Ağır Suçlar Suikast", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
	// {isim : "Ağır Suçlar Suikast Girişimi", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
	// {isim : "Ağır Suçlar Organize Suç Örgütü Kuran", para : 0, hapis :0, kamu :0, illegal : false, active : false, tceza : 0 },
	
]